[phases.setup]
nixPkgs = ["python311", "ffmpeg"]

[phases.install]
cmds = ["python3.11 -m venv .venv && . .venv/bin/activate && pip install -r requirements.txt"]

[phases.start]
cmds = [". .venv/bin/activate && uvicorn api:app --host 0.0.0.0 --port 8000"]
